name: Test exiting on failure

on: [push]

jobs:
  fail-test:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        code: [0, -1, 1, 2, 3, 127, -128, 255]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Try to fail
      run: exit ${{ matrix.code }}
      
    - name: Succeeded
      run: echo No fail for ${{ matrix.code }}

  fail-test-n:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        code: [0, -1, 1, 2, 3, 127, -128, 255]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1

    - name: Try to fail (n commands)
      run: | 
        exit ${{ matrix.code }}
        exit 0
        
    - name: Succeeded
      run: echo No fail for ${{ matrix.code }}

